/*
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

import { SpeakeasyBase, SpeakeasyMetadata } from "../../../internal/utils";
import { Expose } from "class-transformer";

export class Post extends SpeakeasyBase {
    /**
     * Body of the post
     */
    @SpeakeasyMetadata()
    @Expose({ name: "body" })
    body?: string;

    /**
     * ID of the post
     */
    @SpeakeasyMetadata()
    @Expose({ name: "id" })
    id?: number;

    /**
     * Title of the post
     */
    @SpeakeasyMetadata()
    @Expose({ name: "title" })
    title?: string;

    /**
     * ID of the user who created the post
     */
    @SpeakeasyMetadata()
    @Expose({ name: "userId" })
    userId?: number;
}
