/*
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

export * from "./deletepostsid";
export * from "./getpostsid";
export * from "./putpostsid";

export * from "./sdkerror";
