/*
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

export * from "./deletepostsid";
export * from "./getposts";
export * from "./getpostsid";
export * from "./postposts";
export * from "./putpostsid";
